In [1]:
import numpy as np

In [4]:
A = np.array([[2, 3], [1, 4]])
determinant = np.linalg.det(A)
print("determinant:\n", determinant)

inverse = np.linalg.inv(A)
print("inverse:\n", inverse)

my_i = np.dot(A, inverse)
print("my_i:\n", my_i)

determinant:
 5.000000000000001
inverse:
 [[ 0.8 -0.6]
 [-0.2  0.4]]
my_i:
 [[1. 0.]
 [0. 1.]]


In [6]:
# Eigenvalues and Eigenvectors

eigenvalues, eigenvectors = np.linalg.eig(A)
print("eigenvalues:\n", eigenvalues)
print("eigenvectors:\n", eigenvectors)

B = np.array([[4, 2], [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(B)
print("eigenvalues:\n", eigenvalues)
print("eigenvectors:\n", eigenvectors)



eigenvalues:
 [1. 5.]
eigenvectors:
 [[-0.9486833  -0.70710678]
 [ 0.31622777 -0.70710678]]
eigenvalues:
 [4.56155281 0.43844719]
eigenvectors:
 [[ 0.96276969 -0.48963374]
 [ 0.27032301  0.87192821]]


In [7]:
# Matrix Decomposition
# Singular Value Decomposition
# A = U * S * V
# U and V are orthogonal matrices
# S is a diagonal matrix
# The singular values are the diagonal values of S
U, S, vt = np.linalg.svd(A)
print("U:\n", U)
print("S:\n", S)
print("vt:\n", vt)


U:
 [[-0.65520174 -0.75545395]
 [-0.75545395  0.65520174]]
S:
 [5.39834564 0.92620968]
vt:
 [[-0.38268343 -0.92387953]
 [-0.92387953  0.38268343]]


In [10]:
# Excercise 1: Calculate the determinant of the following matrix
C = np.array([[2, 3, 4], [4, 5, 6], [7, 8, 9]])
determinant = np.linalg.det(C)
print("determinant:\n", determinant)

# Excercise 1b: Calculate the inverse of the following matrix
D = np.array([[2, 3, 4], [4, 5, 6], [7, 8, 9]])
inverse = np.linalg.inv(D)
print("inverse:\n", inverse)


determinant:
 -7.61295788314396e-16
inverse:
 [[ 3.94064967e+15 -6.56774946e+15  2.62709978e+15]
 [-7.88129935e+15  1.31354989e+16 -5.25419957e+15]
 [ 3.94064967e+15 -6.56774946e+15  2.62709978e+15]]


In [11]:
# Excercise 2: Calculate the eigenvalues and eigenvectors of the following matrix
E = np.array([[4, -2], [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(E)
print("eigenvalues:\n", eigenvalues)
print("eigenvectors:\n", eigenvectors)



eigenvalues:
 [3. 2.]
eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [15]:
# Excersice 3: Calculate the singular value decomposition of the following matrix
F = np.array([[3, 1, 1], [-1, 3, 1], [1, 1, 3]])
U, S, vt = np.linalg.svd(F)
print("U:\n", U)
print("S:\n", S)
print("vt:\n", vt)

# Resconstruct
sigma = np.zeros((3, 3))
np.fill_diagonal(sigma, S)
reconstructed = np.dot(U, np.dot(sigma, vt))
print("reconstructed:\n", reconstructed)

reconstructed = U @ sigma @ vt
print("reconstructed:\n", reconstructed)

U:
 [[-0.57735027  0.57735027 -0.57735027]
 [-0.4412247  -0.81558342 -0.37435872]
 [-0.68701342  0.03860509  0.7256185 ]]
S:
 [4.48261292 3.17102979 1.68841687]
vt:
 [[-0.4412247  -0.57735027 -0.68701342]
 [ 0.81558342 -0.57735027 -0.03860509]
 [-0.37435872 -0.57735027  0.7256185 ]]
reconstructed:
 [[ 3.  1.  1.]
 [-1.  3.  1.]
 [ 1.  1.  3.]]
reconstructed:
 [[ 3.  1.  1.]
 [-1.  3.  1.]
 [ 1.  1.  3.]]
