In [1]:
import numpy as np

In [13]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Addition:\n", A + B)
print("Subtraction:\n", A - B)

C = 2 * A
print("Scalar multiplication:\n", C)

print("Element-wise multiplication:\n", A * B)

result = np.dot(A, B)
print("Matrix multiplication:\n", result)

I = np.eye(2)
print("Identity matrix:\n", I)


Z = np.zeros((2))
print("Zero matrix:\n", Z)

D = np.diag([1, 2, 3])
print("Diagonal matrix:\n", D)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Scalar multiplication:
 [[2 4]
 [6 8]]
Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication:
 [[19 22]
 [43 50]]
Identity matrix:
 [[1. 0.]
 [0. 1.]]
Zero matrix:
 [0. 0.]
Diagonal matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [20]:
# Excercise 1: Create Vectors and Matrices Using Numpy

import numpy as np

# Create a 2x2 matrix
A = np.array([[1, 2], [3, 4]])
B = np.array([[9, 8], [7, 6]])
print("Matrix A:\n", A)
print("Matrix B:\n", B)

# addition
print("Addition:\n", A + B)

# subtraction
print("Subtraction:\n", B- A)

# Scalar multiplication
print("Scalar multiplication:\n", 2 * A)

# Element-wise multiplication
print("Element-wise multiplication:\n", A * B)

# Matrix multiplication
result = np.dot(A, B)
print("Matrix multiplication:\n", result)



Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[9 8]
 [7 6]]
Addition:
 [[10 10]
 [10 10]]
Subtraction:
 [[8 6]
 [4 2]]
Scalar multiplication:
 [[2 4]
 [6 8]]
Element-wise multiplication:
 [[ 9 16]
 [21 24]]
Matrix multiplication:
 [[23 20]
 [55 48]]


In [22]:
# Excercise 2: Implement matrix vector multiplication using numpy

# create matrix and vector
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
V = np.array([1, 0, -1])

# Matrix vector multiplication
result = np.dot(M, V)
print("Matrix vector multiplication:\n", result)

Matrix vector multiplication:
 [-2 -2 -2]


In [24]:
# Excercise 3: Explore Special Matrices

# Identity matrix
I = np.eye(3)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.dot(A, I)
print("Identity matrix:\n", I)
print("Matrix multiplication with identity matrix:\n", result)

# Zero matrix
Z = np.zeros((3, 3))
print("Zero matrix:\n", Z)

# Diagonal matrix
D = np.diag([1, 2, 3])
print("Diagonal matrix:\n", D)


Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matrix multiplication with identity matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Zero matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Diagonal matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
