In [1]:
import numpy as np

In [2]:
a = np.arange(1,6)
b = np.arange(6,11)

print(a)
print(b)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [3]:
print("Add: ", a+b)
print("Subtract: ", a-b)
print("Multiply: ", a*b)
print("Divide: ", a/b)

Add:  [ 7  9 11 13 15]
Subtract:  [-5 -5 -5 -5 -5]
Multiply:  [ 6 14 24 36 50]
Divide:  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [6]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(f"matrix: {matrix}")
transpose = matrix.T
print(f"transpose: {transpose}")


matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]
transpose: [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
another_matrix = np.array([[9,8,7], [6,5,4], [3,2,1]])
print(f"Addition of two matrices: {matrix + another_matrix}")
print(f"Multiplication of two matrices: {matrix * another_matrix}")


Addition of two matrices: [[10 10 10]
 [10 10 10]
 [10 10 10]]
Multiplication of two matrices: [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [13]:
# create a 4x4 matrix and calculate the sum of its columns
matrix = np.random.rand(4,4)
print(f"matrix: {matrix}")
sum_of_columns = np.sum(matrix, axis=0)
print(f"Sum of columns: {sum_of_columns}")

# write a program to normalize an array (scale values between 0 and 1)
array = np.array([1,2,3,4,5])
print(f"array: {array}")
normalized_array = np.interp(array, (array.min(), array.max()), (0, 1))
print(f"normalized array: {normalized_array}")

# Generate a radom array and find its min and max values
array = np.random.rand(10)
print(f"array: {array}")
min_value = np.min(array)
max_value = np.max(array)
print(f"min value: {min_value}")
print(f"max value: {max_value}")


matrix: [[0.0470673  0.65355656 0.43696305 0.01314567]
 [0.5285585  0.33070527 0.91493405 0.14353839]
 [0.01027014 0.82881821 0.3142861  0.98765292]
 [0.26983642 0.54831709 0.67475154 0.81464464]]
Sum of columns: [0.85573236 2.36139713 2.34093474 1.95898162]
array: [1 2 3 4 5]
normalized array: [0.   0.25 0.5  0.75 1.  ]
array: [0.74524539 0.45894292 0.42817598 0.51125894 0.03475223 0.69574077
 0.29651397 0.13224047 0.80228683 0.50089289]
min value: 0.034752231003280065
max value: 0.8022868289121667
