In [2]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3])
print(arr + 10)

[11 12 13]


In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([1, 0, 1])
print(matrix + vector)

[[2 2 4]
 [5 5 7]]


In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Sum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Min: {np.min(arr)}")
print(f"Std: {np.std(arr)}")
print(f"Var: {np.var(arr)}")
print(f"Sum along rows: {np.sum(arr, axis=1)}")
print(f"Sum along columns: {np.sum(arr, axis=0)}")


Sum: 21
Mean: 3.5
Max: 6
Min: 1
Std: 1.707825127659933
Var: 2.9166666666666665
Sum along rows: [ 6 15]
Sum along columns: [5 7 9]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6])

evens = arr[arr % 2 == 0]
print(evens)

arr[arr > 3]  = 0
print(f"Modified array: {arr}")

[2 4 6]
Modified array: [1 2 3 0 0 0]


In [20]:
np.random.seed(42)
random_array = np.random.rand(3, 3)
print(f"Random array: \n{random_array}")

random_integers = np.random.randint(0, 10, (2, 3))
print(f"Random integers: \n{random_integers}")


Random array: 
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
Random integers: 
[[7 2 5]
 [4 1 7]]


In [22]:
# excercise 1
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Matrix: \n{matrix}")
vector = np.array([1, 0, -1])
print(f"Vector: {vector}")

result_addition = matrix + vector
print(f"Result of addition: \n{result_addition}")
result_multiplication = matrix * 2
print(f"Result of multiplication: \n{result_multiplication}")


Matrix: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector: [ 1  0 -1]
Result of addition: 
[[2 2 2]
 [5 5 5]
 [8 8 8]]
Result of multiplication: 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [31]:
# excercise 2

dataset = np.random.randint(1,51, size=(5,5))
print(f"Original dataset:\n {dataset}")
# filter values greater than 25
dataset[dataset > 25] = 0
print(f"Modified dataset:\n {dataset}")
# calculate summary stats
print(f"Sum: {np.sum(dataset)}")
print(f"Mean: {np.mean(dataset)}")
print(f"Standard deviation: {np.std(dataset)}")


Original dataset:
 [[35 38 13 47 25]
 [ 9  4 14 37 34]
 [11 41  3 28 29]
 [ 9  3 25 34 12]
 [42  9 15 40 25]]
Modified dataset:
 [[ 0  0 13  0 25]
 [ 9  4 14  0  0]
 [11  0  3  0  0]
 [ 9  3 25  0 12]
 [ 0  9 15  0 25]]
Sum: 177
Mean: 7.08
Standard deviation: 8.375774591045296


In [34]:
# additional practice

# Create a 3d random array and compute statistics along specified axis
arr = np.random.rand(3, 3, 3)
print(f"3D array: \n{arr}")

mean_x = np.mean(arr, axis=0)
mean_y = np.mean(arr, axis=1)
mean_z = np.mean(arr, axis=2)

print(f"Mean along x-axis: \n{mean_x}")
print(f"Mean along y-axis: \n{mean_y}")
print(f"Mean along z-axis: \n{mean_z}")



3D array: 
[[[0.54126658 0.962992   0.34187217]
  [0.63262189 0.93202811 0.10250973]
  [0.93722849 0.68788572 0.06783706]]

 [[0.30096357 0.70817209 0.0673506 ]
  [0.58217046 0.34588306 0.62091552]
  [0.04574203 0.87153681 0.97348897]]

 [[0.96887786 0.74965183 0.13008624]
  [0.7582632  0.02458692 0.02212355]
  [0.32361022 0.48864319 0.77040742]]]
Mean along x-axis: 
[[0.60370267 0.80693864 0.17976967]
 [0.65768518 0.43416603 0.24851627]
 [0.43552691 0.68268857 0.60391115]]
Mean along y-axis: 
[[0.70370565 0.86096861 0.17073965]
 [0.30962535 0.64186398 0.55391836]
 [0.68358376 0.42096065 0.30753907]]
Mean along z-axis: 
[[0.61537692 0.55571991 0.56431709]
 [0.35882875 0.51632301 0.63025594]
 [0.61620531 0.26832455 0.52755361]]


In [35]:
# write a program to generate a dataset from random floats and normalize the values between 0 and 1
arr = np.random.rand(3, 3)
print(f"Original array: \n{arr}")
arr_min = np.min(arr)
arr_max = np.max(arr)
normalized = (arr - arr_min) / (arr_max - arr_min)
print(f"Normalized array: \n{normalized}")



Original array: 
[[0.68329538 0.44590271 0.27362667]
 [0.9971245  0.4261813  0.45138702]
 [0.16362382 0.79480955 0.69368223]]
Normalized array: 
[[0.62348066 0.33866665 0.13197691]
 [1.         0.31500572 0.34524651]
 [0.         0.7572708  0.63594238]]


In [48]:
# implement conditional replacement to create a binary mask for values above a threshold

arr = np.random.randint(1, 11, size=(10))
print(f"Original array: {arr}")
threshold = 7
# do less than first, othersie they are 1 which is less than the threshold

arr[arr <= threshold] = 0
arr[arr > threshold] = 1
print(f"Binary mask ({threshold}): {arr}")

Original array: [ 7  4  4  6 10  6 10  3  9 10]
Binary mask (7): [0 0 0 0 1 0 1 0 1 1]
